강원대 BE_4조 3주차 제출
kakao-tech-campus-2nd-step3/Team4_BE pull request #13
Opened 2024-09-20 10:12 UTC by noojmogstel

## 👨🏼‍🏫 멘토님께 여쭈어보고싶은점

- 현재 Weekly - Devlop - Master - Reivew 순으로 PR을 보내고 병합을 하였는데, PR 제목이나 내용, 추가로 들어가면 좋을 점 어떤게 있을지 조언해 주시면 감사하겠습니다!
- Controller - Service간 데이터 교환시  DTO가 따로 필요한지, 현재는 Service에서 ResponseDTO를 직접 반환하는 형태인데 좀 의존적(?) 만약 새로운 형태의 Response가 필요할 시 Service의 메서드를 추가하는 형태가 아니라 DTO to ResponseDTO의 형태가 되는것이 좀 더 올바른 방향일지?
- 전체적으로, 협업을 하는 과정에서 더 나은 코드 스타일에 대해 많이 생각하게 되는 것 같습니다. 보시기에 이 부분은 이런식으로 짜는게 더 좋을것 같다 라고 생각드시는점 있으시면 말씀해주시면 감사하겠습니다.

## 🗓︎ 3주차 구현내용

API문서와 ERD 설계를 기반으로 Auth, User, Trainer API를 구현하였습니다.

### 공통

[코드 레이어]

Controller, Service, Repository, DTO(Response, Request)

[ 기술 스택 ]

로그인 인증: 토큰방식(JWT 라이브러리 사용)레포지토리: JPA사용

### Auth API

- 일반회원, 트레이너의 로그인 API 작성.
- JWT Util - JWT 관련 로직 작성

### User API

- User 관련 Profile, Info API 작성
- 

### Trainer API

- Trainer 관련 Profile, Career API 작성

2024-09-22 07:10 UTC, leaf-upper commented
**1 . 현재 Weekly - Devlop - Master - Reivew 순으로 PR을 보내고 병합을 하였는데, PR 제목이나 내용, 추가로 들어가면 좋을 점 어떤게 있을지 조언해 주시면 감사하겠습니다!**

PR이 어떤 부분에 대한 기능 구현인지, 혹시 연관된 Issue가 있다면 Issue Link를 같이 첨부해주시면 이해가 쉬울것 같습니다.
또한 Self-Code Review를 해주시면 너무 좋을것 같습니다. 직접 PR 코드를 보시고 이해가 어렵겠다싶은 부분에 대해서는 코멘트를 먼저 달아주시면 리뷰하는 입장에서 좀더 마음편히 리뷰드릴 수 있을것 같아요.

**2. Controller - Service간 데이터 교환시 DTO가 따로 필요한지, 현재는 Service에서 ResponseDTO를 직접 반환하는 형태인데 좀 의존적(?) 만약 새로운 형태의 Response가 필요할 시 Service의 메서드를 추가하는 형태가 아니라 DTO to ResponseDTO의 형태가 되는것이 좀 더 올바른 방향일지?**

다른조에도 비슷한 리뷰를 드렸는데요~

일반적인 스프링 계층구조, Controller -> Service -> Repository의 흐름에서 저는 DTO가 2가지 타입이 있다고 생각하는데요,
Controller 계층의 DTO가 있고, Service 계층의 DTO가 있습니다. Service 계층의 DTO라면, Service에서 수행해도 좋습니다.
다만 Controller 계층의 DTO라면, Controller 계층에서 변환을 수행해야합니다.

ResponseDTO는 Service 계층의 DTO라기보다는, HTTP와 연관된 내용일것 같으니, Controller 계층의 DTO가 맞을것 같아요. 이런 경우 변환은 Controller에서 해주시면 좋습니다. (서비스 계층에서는 ServiceDTO 혹은 Entity 자체를 반환하셔도 좋습니다. 다만 Entity를 반환하는 경우 JPA의 open session in view가 꺼져있는지 체크해주세요.)

Controller <-> Service 간 데이터 교환시 사용하는 DTO는 Service DTO가 될것 같아요. Service Dto 또한 Controller에서 변환을 해주셔야합니다.

Controller -> Service -> Entity 해당 의존성의 방향대로, Service가 Controller의 DTO를 사용하지 않게끔 코드를 작성해주시면 좋을것 같아요! 

**3. 전체적으로, 협업을 하는 과정에서 더 나은 코드 스타일에 대해 많이 생각하게 되는 것 같습니다. 보시기에 이 부분은 이런식으로 짜는게 더 좋을것 같다 라고 생각드시는점 있으시면 말씀해주시면 감사하겠습니다.**

넵 이부분은 코드를 보면서 말씀드리도록 하겠습니다.

2024-09-22 07:29 UTC, leaf-upper requested changes
안녕하세요~ 코드리뷰 1회차인데 고생 많으셨습니다 👍 👍 
코드를 봤는데요~ 아직 미숙한 부분이 많이 있는것 같아요.
코드 컨벤션은 꼭 지켜주셨으면 합니다. 같이 개발을 하실때 컨벤션이 맞춰지지 않으면 이후에 개발하기 점점 어려워지실거예요. 컨벤션과 관련되서 몇가지 코멘트 드린부분에 대해서만 수정과 gitignore를 다시 한번 확인후 수정해주시면 어프로브 드릴게요~
고생 많으셨습니다 👍

2024-09-22 07:29 UTC, leaf-upper commented on .gitignore
> +.idea
.idea가 제대로 빠지지 않을것 같아요~ 
한번 commit되면 gitignore에 추가되더라도 해당 파일은 계속 버전관리가 되게 됩니다. 이부분은 한번 다시 봐주세요~

2024-09-22 07:29 UTC, leaf-upper commented on build.gradle
> +	id 'java'
다른조에도 비슷한 코멘트를 드렸는데요~
빌드 스크립트에서 의존성에 대한 버전관리를 변수로 하면, 도움이 될때가 많아서 이런방식도 추천해드립니다~
buildscript {
    ext {
        spring_boot_version = '3.3.3'
        spring_dependency_management = '1.1.6'
    }

    repositories {
        mavenCentral()
    }
}

plugins {
    id 'java'
    id 'org.springframework.boot' version "${spring_boot_version}"
    id 'io.spring.dependency-management' version "${spring_dependency_management}"
}

2024-09-22 07:29 UTC, leaf-upper commented on build.gradle
> +    implementation 'software.amazon.awssdk:auth:2.20.0'
인덴테이션은 맞춰주세요~~!

2024-09-22 07:29 UTC, leaf-upper commented on src/main/java/linkfit/config/AmazonS3ClientConfig.java
> +    @Value("${cloud.aws.credentials.access-key}")
이 변수 3개는 Properties 클래스로 별도 관리해도 좋을것 같아요.
record라는 신규 자바 문법도 나왔으니, 해당 문법을 사용하여 프로퍼티 클래스를 만들고,
@EnableConfigurationProperties
@ConfigurationProperties
위 2개 애너테이션을 사용해보셔도 좋을것 같습니다.

2024-09-22 07:29 UTC, leaf-upper commented on src/main/java/linkfit/controller/AuthController.java
> +    public ResponseEntity<Void> userRegister(
메서드명은 행위를 나타내는 동사로 시작하는게 좋아요. registerUser, loginUser, registerTraniner 이런식으로 리팩토링 해주시면 좋을것 같습니다.

2024-09-22 07:29 UTC, leaf-upper commented on src/main/java/linkfit/dto/RegisterRequest.java
> +public class RegisterRequest<T extends PersonEntity> {
abstract class로 사용해주시면 좋을것 같아요~
최근에는 sealed 와 관련된 기능도 추가되었으니 같이 공부해보시면 좋겠네요!

2024-09-22 07:29 UTC, leaf-upper commented on src/main/java/linkfit/dto/CareerRequest.java
> +public class CareerRequest {
request, response와 같이 데이터를 표현하는 객체는 record를 사용해도 좋을것 같아요.

2024-09-22 07:29 UTC, leaf-upper commented on src/main/java/linkfit/entity/Career.java
> +    public Career() {
기본생성자는 protected 접근제어자로 제한해주시면 좋을것 같아요. 요건 모든 Entity에 대해서 그렇게 작성해주세요~

2024-09-22 07:29 UTC, leaf-upper commented on src/main/java/linkfit/entity/Trainer.java
> +@Table(name = "Trainers")
테이블명 네이밍 컨벤션은 파스칼 케이스인가요?

2024-09-22 07:29 UTC, leaf-upper commented on src/main/java/linkfit/entity/PersonEntity.java
> +public class PersonEntity {
요것도 추상클래스로 가면 좋을것 같아요

2024-09-22 07:29 UTC, leaf-upper commented on src/main/java/linkfit/repository/UserRepository.java
> +	Optional<User> findByEmail(String email);
email에 데이터베이스 Index가 필요하겠네요

2024-09-22 07:29 UTC, leaf-upper commented on src/main/java/linkfit/service/AuthService.java
> +    public void register(RegisterRequest<T> request, MultipartFile profileImage) {
`@Transactional` 애너테이션을 사용해보는것도 좋을것 같아요.

2024-09-22 07:29 UTC, leaf-upper commented on src/main/java/linkfit/service/ImageUploadService.java
> +    public <T extends PersonEntity> void profileImageSave(T entity, MultipartFile profileImage) {
메서드명은 위에서 말한것처럼 동사로 시작해주세요~

2024-09-22 07:29 UTC, leaf-upper commented on src/main/java/linkfit/service/ImageUploadService.java
> +    private String bucket;
이부분도 위에서 말씀드린것처럼 프로퍼티 클래스로 표현할수있겠네요

2024-09-22 07:29 UTC, leaf-upper commented on src/main/java/linkfit/service/UserService.java
> +	private final JwtUtil jwtUtil;
인덴테이션이 안맞는것 같아요~

2024-09-22 07:29 UTC, leaf-upper commented on src/main/java/linkfit/util/JwtUtil.java
> +    private final long expirationMs;
expirationMs는 설정값으로 빼는게 좋을것 같아요~

2024-09-22 07:29 UTC, leaf-upper commented on src/main/java/linkfit/service/CareerService.java
> +    public void deleteCareer(Long careerId) {
제 경험상 서비스를 구현할때 데이터를 정말 삭제하는일은 많지 않은것 같아요.
Status값을 두고, Soft Delete 하는것도 괜찮은 방법입니다~

2024-09-23 05:34 UTC, noojmogstel commented on .gitignore
> +.idea
말씀해주신 부분 관련 알아보았는데, 
.idea에는 프로젝트의 버전 등이 포함되어 있는데, 이것이 중복되어 commit 될 경우, 본인 혹은 타 사용자가 clone하여 사용할 시 버전 충돌이 발생할 수 있어,
.idea를  `git rm --cached -r .idea` 명령어로 삭제하고 다시커밋하는걸로 해결하는것으로 이해했는데 맞게 이해했는지 여쭈어보고싶습니다!

2024-09-23 08:25 UTC, noojmogstel commented on src/main/java/linkfit/config/AmazonS3ClientConfig.java
> +    @Value("${cloud.aws.credentials.access-key}")
#27 
관련 피드백주신점 코드를 작성해보았습니다! 곧바로 적용하기보다 한번 검증받고 적용하는것이 좋을것같아서 작성해보았습니다! 번거로우시겠지만 확인해주신다면 감사하겠습니다!🙇

2024-09-23 14:23 UTC, leaf-upper commented on .gitignore
> +.idea
.idea에는 사용자별로 Intellij 설정이 들어가는 디렉터리라서 코드버전관리의 대상이 되지 않아도 되어요~
말씀하신부분이 맞습니다! `git rm --cached -r .idea ` 부탁드려요!~

2024-09-24 00:25 UTC, noojmogstel commented on .gitignore
> +.idea
넵 답변 감사합니다!! :)

2024-09-26 09:02 UTC, leaf-upper commented on src/main/java/linkfit/controller/AuthController.java
> +        @RequestPart("user") UserRegisterRequest request,
API 요청이 정상적으로 끝났다면 Empty Body를 리턴하기보다는,  아무의미가 없더라도, 생성된 유저의 ID값이라도 반환하면 좋을것 같아요!

2024-09-26 09:03 UTC, leaf-upper commented on src/main/java/linkfit/dto/RegisterRequest.java
> +public class RegisterRequest<T extends Person> {
추상클래스로도 사용할 수 있을까요?

2024-09-26 09:10 UTC, leaf-upper commented on src/main/java/linkfit/service/AuthService.java
> +public class AuthService<T extends Person> {
제네릭을 이용해서 타입별(User,Traniner, Persion 등등)로 AuthService, PersionService를 코드 공통화 시키는건 좋지만,
차라리 인터페이스를 사용해보시면 어떨까요?

2024-09-26 09:10 UTC, leaf-upper commented on src/main/java/linkfit/util/JwtUtil.java
> +	private final SecretKey secretKey;
요기는 아직 인덴테이션이 안맞네요~

2024-09-26 09:11 UTC, leaf-upper approved these changes
👍 코드리뷰 1회차 고생많으셨습니다!~

2024-09-26 09:11 UTC, merged

2024-09-26 09:43 UTC, noojmogstel commented
감사합니다! 추가적으로 말씀해주신 부분은 다음 코드리뷰 전까지 반영해놓도록 하겠습니다!